version: '3.3'

volumes:
  data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    image: kasylin/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: kasylin/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    env_file: .env
    image: kasylin/foodgram_infra
    ports:
      - "8080:80"
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - static:/static/
      - media:/media/